### ISSUE TITLE
tags的效果怎么才能实现示例的效果？

### ISSUE THREAD

**Issue by izumi96** [SumiMakito/hexo-theme-Journal#20]
我的tags总是空白的，而且会显示在侧边栏，但是我想实现示例的效果，怎么修改配置文件？

**Comment by izumi96** [comment]
控制台那里没有路由到tag-index.ejs

**Comment by AmazingRise** [comment]
用命令`hexo new page "tags"`新建一个页面.
然后编辑`source/tags/index.md`,替换为以下内容即可:
```yaml
---
title: 标签
layout: tag-index
no_comments: true
---
```
其中,`title`可以自定义为任何内容.

分类页同理,需要将`layout`改为`category-index`.
